Release prepare 1.1.2
NIFCLOUD-mbaas/ncmb_swift pull request #74
Opened 2020-09-02 02:46 UTC by kobayashi-masaya

SDKの改善にご協力いただきありがとうございます。  
(Thank you for your support our SDK.)

プルリクエストを作成する場合は、developをターゲットにしてください。  
(Please select target branch to "develop" branch.)

可能な限り、修正時にはテストコードまたは動作確認手順を追加してください。  
(Please include test code or describe confirmation steps as possible.)

## 概要(Summary)

- Fixed #xx

## 動作確認手順(Step for Confirmation)

Run the unit test.

2020-09-02 08:29 UTC, ncmbadmin reviewed
1点コメントがありますので、ご確認いただけますでしょうか。

2020-09-02 08:29 UTC, ncmbadmin commented on NCMB.podspec
> +  s.version      = "1.1.2"
バージョンの変更について、1点漏れたかと思いますので、ご確認いただけますでしょうか。

ファイル：NCMB/NCMB.swift
```
    public static let SDK_VERSION : String = "1.1.1"
```

ファイル：NCMBTests/NCMBInstallationTests.swift
```
XCTAssertTrue(String(data: manager.saveLog[0].data, encoding: .utf8)!.contains("\"sdkVersion\":\"1.1.1\""))
```

2020-09-02 09:28 UTC, kobayashi-masaya commented on NCMB.podspec
> +  s.version      = "1.1.2"
すみません。漏れていたので追加いたしました。

2020-09-03 00:14 UTC, ncmbadmin reviewed
1点コメントがありますので、ご確認ください。

2020-09-03 00:14 UTC, ncmbadmin commented on NCMBTests/network/NCMBRequestTests.swift
> +        XCTAssertEqual(urlRequest.value(forHTTPHeaderField:"X-NCMB-SDK-Version"), "swift-1.1.2")
ご対応ありがとうございます。レビューコメント漏れたのですが、以下のところも修正必要だと思いますので、
追加ご対応いただけますでしょうか。

NCMBTests/network/NCMBRequestTests.swift
```
        XCTAssertEqual(urlRequest.value(forHTTPHeaderField:"X-NCMB-SDK-Version"), "swift-1.1.1")
```

2020-09-03 00:58 UTC, kobayashi-masaya commented on NCMBTests/network/NCMBRequestTests.swift
> +        XCTAssertEqual(urlRequest.value(forHTTPHeaderField:"X-NCMB-SDK-Version"), "swift-1.1.2")
追加いたしましたので再度ご確認をお願いいたします。

2020-09-03 01:06 UTC, ncmbadmin approved these changes
バージョン更新対応ありがとうございます。更新内容を確認しました。
問題がありません。

2020-09-03 01:07 UTC, morisatoru commented
テスト失敗してますよ。一通りテストを流してからコミットするようにお願いいたします。

2020-09-03 01:08 UTC, morisatoru reviewed
テスト失敗
https://github.com/NIFCLOUD-mbaas/ncmb_swift/pull/74#discussion_r482632815

2020-09-03 01:11 UTC, ncmbadmin requested changes
再度テストを確認する必要があります

2020-09-03 01:18 UTC, morisatoru commented
> テスト失敗
> [#74 (comment)](https://github.com/NIFCLOUD-mbaas/ncmb_swift/pull/74#discussion_r482632815)

テストが通ったことを確認

2020-09-03 01:19 UTC, morisatoru commented
> テスト失敗してますよ。一通りテストを流してからコミットするようにお願いいたします。

解消したことを確認

2020-09-03 01:25 UTC, ncmbadmin approved these changes
テストも正常に通ったことを確認しました。

2020-09-03 01:26 UTC, merged

2020-09-03 01:34 UTC, kobayashi-masaya commented on NCMBTests/network/NCMBRequestTests.swift
> +        XCTAssertEqual(urlRequest.value(forHTTPHeaderField:"X-NCMB-SDK-Version"), "swift-1.1.2")
すみません。テストを通すように心がけます。